<h1 class="Title">www.mehdibaileche-cooker.com </strong></h1>
	
<!-- Présentation -->
<section class="first">
	<!-- Vidéo -->
		<article>
			<iframe src="https://www.youtube.com/embed/T9hm-5jg0hE"></iframe>
		</article>
	<!-- Message accueil -->
		<article>
			<h2>Découvrez les dernières créations du Chef ! </h2>
			<div>
				<p>"Adobe et ses fournisseurs utilisent les cookies et des technologies similaires pour améliorer votre expérience et mesurer vos interactions avec nos sites web, nos produits et nos services. Nous pouvons ainsi vous fournir. Vous pouvez aussi cliquer sur « Personnaliser » pour restreindre le partage et voir nos fournisseurs. Vous pouvez modifier ces choix à tout moment."</p>
				<h4>Mehdi Baileche</h4>
			</div>
		</article>
</section>

<!-- Si Login -->
<?php if (array_key_exists( 'firstName', $_SESSION )):?>
		
	<!-- Articles -->
	<section class="second">

		<h1> Articles</h1>
		<!-- Formulaire -->
		<form method="post"  action="index.php" enctype="multipart/form-data">
		<!-- Jquery slider.js -->
			<article class="articles-Slider">
				<!-- Afficher Article -->
				<?php foreach($result_Articles as $article): ?>
					<div class="cards">
						<div class="card">									

							<!-- IMG -->
							<div class="image">
							  <img src="img/articles/<?php echo $article['Img']; ?>" alt="image article"/>
							</div>

							<!-- TITLE -->
							<div class="title">
							    <a href="#" class="toggle-info btn-slider" title="cliquez ici">
							    	<span class="left"></span>
							    	<span class="right"></span>
							  	</a>
							  	<h3><?= htmlspecialchars($article['Title']) ?></h3>
							  	<p> <?= nl2br(htmlspecialchars($article['CreationDate'])) ?></p>
							</div>

							<!-- CONTENT HIDDEN -->
							<div class="card-flap flap1">
								<div class="card-description">
									<p class="content"><?= nl2br(htmlspecialchars($article['Content'])) ?></p>
									<p><?= nl2br(htmlspecialchars($article['Author'])) ?></p>
								</div>
							</div>

						</div><!-- /card -->
					</div><!-- /cards -->
				<?php endforeach; ?>
			</article>
		</form>
	</section>

	<!-- Commentaires -->
	<section class="third">
		<h1>Commentaires</h1>
		
		<!-- Ajouter post -->
		<article class="postComment">
			<form method="post"  action="index.php" enctype="multipart/form-data">
				<input type="hidden" name="postId" value="<?= $_SESSION['id']; ?>">
				<input type="hidden" name="author" value="<?= $_SESSION['firstName'] ?>">
				<button class="btn-blue" type="submit">Ajouter</button>
				<textarea value=" jshgcjezg" name="content"  rows="2" required>
				</textarea>
			</form>      
		</article>	

		<!-- View post -->
		<article class="bubble scroller">
			<form method="post"  action="index.php" enctype="multipart/form-data">
				<?php foreach($result_Comm as $comment): ?> 
					<div class="bubble-text">
						<h4><?= nl2br(htmlspecialchars($comment['Comm_Content'])) ?></h4>
						<h5><?= nl2br(htmlspecialchars($comment['Comm_Author'])) ?></h5>	
						<hr>
						<img src="img/avatars/<?php echo $comment['Comm_Img']; ?>" alt="image user"/>
					</div>
				<?php endforeach; ?>
			</form> 
		</article>
	</section>

<?php endif ?>
